name: frost_env
channels:
  - defaults
dependencies:
  - python=3.10
  - numpy
  - xarray
  - dash
  - rioxarray
  - pip:
    - utm
    - pyvista
    - gstools
    - git+https://github.com/instructed-glacier-model/igm@v3.0.1

