name: frost_env
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - ansi2html=1.9.1
  - blas=1.0
  - blinker=1.9.0
  - bottleneck=1.4.2
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - certifi=2025.7.14
  - charset-normalizer=3.3.2
  - click=8.1.8
  - dash=2.14.2
  - expat=2.7.1
  - flask=3.0.3
  - flask-compress=1.13
  - idna=3.7
  - importlib-metadata=8.5.0
  - intel-openmp=2023.1.0
  - itsdangerous=2.2.0
  - jinja2=3.1.6
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - markupsafe=3.0.2
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - narwhals=1.31.0
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - numexpr=2.10.1
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openssl=3.0.17
  - packaging=24.2
  - pandas=2.2.3
  - pip=25.1
  - plotly=6.0.1
  - pthread-stubs=0.3
  - pysocks=1.7.1
  - python=3.10.18
  - python-dateutil=2.9.0post0
  - python-tzdata=2025.2
  - pytz=2024.1
  - readline=8.2
  - requests=2.32.3
  - retrying=1.3.3
  - setuptools=78.1.1
  - six=1.17.0
  - sqlite=3.45.3
  - tbb=2021.8.0
  - tk=8.6.14
  - typing_extensions=4.12.2
  - tzdata=2025b
  - urllib3=2.3.0
  - werkzeug=3.0.6
  - wheel=0.45.1
  - xarray=2024.11.0
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zipp=3.21.0
  - zlib=1.2.13
  - pip:
      - absl-py==2.3.0
      - affine==2.4.0
      - antlr4-python3-runtime==4.9.3
      - astunparse==1.6.3
      - attrs==25.3.0
      - cachetools==5.5.2
      - cftime==1.6.4.post1
      - click-plugins==1.1.1
      - cligj==0.7.2
      - configobj==5.0.9
      - contourpy==1.3.2
      - cycler==0.12.1
      - emcee==3.1.6
      - flatbuffers==25.2.10
      - fonttools==4.58.1
      - gast==0.6.0
      - geopandas==1.1.0
      - google-auth==2.40.2
      - google-auth-oauthlib==1.2.2
      - google-pasta==0.2.0
      - grpcio==1.71.0
      - gstools==1.7.0
      - gstools-cython==1.1.0
      - h5py==3.13.0
      - hankel==1.2.2
      - hydra-core==1.3.2
      - importlib-resources==6.5.2
      - joblib==1.5.1
      - keras==2.15.0
      - kiwisolver==1.4.8
      - libclang==18.1.1
      - markdown==3.8
      - markdown-it-py==3.0.0
      - matplotlib==3.10.3
      - mdurl==0.1.2
      - meshio==5.3.5
      - ml-dtypes==0.3.2
      - mpmath==1.3.0
      - netcdf4==1.6.0
      - nvidia-cublas-cu12==12.2.5.6
      - nvidia-cuda-cupti-cu12==12.2.142
      - nvidia-cuda-nvcc-cu12==12.2.140
      - nvidia-cuda-nvrtc-cu12==12.2.140
      - nvidia-cuda-runtime-cu12==12.2.140
      - nvidia-cudnn-cu12==8.9.4.25
      - nvidia-cufft-cu12==11.0.8.103
      - nvidia-curand-cu12==10.3.3.141
      - nvidia-cusolver-cu12==11.5.2.141
      - nvidia-cusparse-cu12==12.1.2.141
      - nvidia-nccl-cu12==2.16.5
      - nvidia-nvjitlink-cu12==12.2.140
      - oauthlib==3.2.2
      - oggm==1.6.2
      - omegaconf==2.3.0
      - opt-einsum==3.4.0
      - pillow==11.2.1
      - protobuf==4.25.8
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pyevtk==1.6.0
      - pygments==2.19.2
      - pyogrio==0.11.0
      - pyparsing==3.2.3
      - pyproj==3.7.1
      - pyyaml==6.0.2
      - rasterio==1.4.3
      - requests-oauthlib==2.0.0
      - rich==14.1.0
      - rsa==4.9.1
      - salem==0.3.11
      - scipy==1.15.3
      - shapely==2.1.1
      - tensorboard==2.15.2
      - tensorboard-data-server==0.7.2
      - tensorflow==2.15.1
      - tensorflow-estimator==2.15.0
      - tensorflow-io-gcs-filesystem==0.37.1
      - termcolor==3.1.0
      - tqdm==4.67.1
      - utm==0.8.1
      - wrapt==1.14.1
